### ISSUE TITLE
Throw 404 when files not found.

### ISSUE THREAD

**Issue by htkoca** [danielgormly/koa2-static-middleware#1]
`ctx.throw(404)`? Currently throws code 500: Internal Server Error

**Comment by danielgormly** [comment]
I'm going to tidy up this module today. I can't reproduce your issue though. Are you able to reproduce the scenario which causes this behaviour? Currently I am getting 404 errors when files are not found, not 500.

**Comment by danielgormly** [comment]
I've made several changes to the code and have integrated some tests. Previously it was failing when not used with `koa-router`, hopefully that's all fixed now!

**Comment by htkoca** [comment]
Turns out it was a module - koa-errors that changed the errors for me - a colleague of mine commited it and I did not notice. But, definitely thanks for updating and replying though :) appreciate it.
